# Generated by Django 2.0.6 on 2018-08-04 19:52

import api.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=8, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(default='')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Address')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('website', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('key', models.CharField(default=api.models.random_string, max_length=128, unique=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.ManyToManyField(to='api.Address')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Company_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default='False')),
                ('is_HR', models.BooleanField(default='True')),
                ('share', models.CharField(blank=True, default='', max_length=4)),
                ('added_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Address', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college_name', models.CharField(max_length=60)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('performance', models.CharField(max_length=3)),
                ('name', models.CharField(default='None', max_length=20)),
                ('type_of_degree', models.CharField(default='None', max_length=20)),
                ('description', models.TextField()),
                ('stream', models.CharField(max_length=32)),
                ('specialise', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default='', max_length=64, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Custom_User')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('following', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('repositories', models.IntegerField()),
                ('handle', models.CharField(max_length=200)),
                ('origanization', models.CharField(max_length=200)),
                ('owned_private_repo', models.CharField(max_length=200)),
                ('origanization_url', models.CharField(max_length=200)),
                ('owned_public_repos', models.IntegerField(default=0)),
                ('collaborators', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hired', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applications', models.IntegerField(default=0)),
                ('selected', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default='False')),
                ('denied', models.BooleanField(default='False')),
                ('allowed', models.BooleanField(default='False')),
                ('is_main', models.BooleanField(default='False')),
                ('status', models.IntegerField(default=1)),
                ('certificate', models.BooleanField(default='False')),
                ('flexible_work_hours', models.BooleanField(default='False')),
                ('letter_of_recommendation', models.BooleanField(default='False')),
                ('free_snacks', models.BooleanField(default='False')),
                ('informal_dress_code', models.BooleanField(default='False')),
                ('PPO', models.BooleanField(default='False')),
                ('stipend_rate', models.CharField(default='None', max_length=20)),
                ('fixed', models.BooleanField(default='False')),
                ('negotiable', models.BooleanField(default='False')),
                ('performance_based', models.BooleanField(default='False')),
                ('deadline', models.DateField()),
                ('start', models.DateField()),
                ('visibility', models.DateField()),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('responsibilities', models.TextField(default='')),
                ('stipend', models.CharField(default='0', max_length=6)),
                ('location', models.CharField(default='New Delhi', max_length=50)),
                ('code', models.CharField(blank=True, default='', max_length=4)),
                ('id_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(max_length=60)),
                ('organization', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=90)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.Intern')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('start', models.DateField(default=datetime.date.today)),
                ('end', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.Intern')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(default='', max_length=50)),
                ('placeholder', models.CharField(default='', max_length=50)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Internship', verbose_name='Internship')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=20, null=True)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='api.College', verbose_name='Sub')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('selected', models.BooleanField(default='False')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Intern')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='api.Internship', verbose_name='Internship')),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='api.Sub')),
            ],
        ),
        migrations.AddField(
            model_name='siteadmin',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='api.Sub'),
        ),
        migrations.AddField(
            model_name='siteadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Custom_User', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='internship',
            name='available',
            field=models.ManyToManyField(blank=True, null=True, related_name='internships', to='api.Sub'),
        ),
        migrations.AddField(
            model_name='internship',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='internship',
            name='company_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Company_User', verbose_name='Company User'),
        ),
        migrations.AddField(
            model_name='internship',
            name='locations',
            field=models.ManyToManyField(to='api.Address'),
        ),
        migrations.AddField(
            model_name='internship',
            name='skills',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='intern',
            name='skills',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='intern',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sub'),
        ),
        migrations.AddField(
            model_name='intern',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Custom_User'),
        ),
        migrations.AddField(
            model_name='github',
            name='intern',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Intern'),
        ),
        migrations.AddField(
            model_name='degree',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='api.Intern'),
        ),
        migrations.AddField(
            model_name='company_user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Custom_User', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='company',
            name='hiring',
            field=models.ManyToManyField(related_name='hiring', to='api.Sub'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.Submission', verbose_name='Submission'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('internship', 'intern')},
        ),
    ]
