# Generated by Django 2.0.6 on 2018-06-25 04:36

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub', models.CharField(max_length=200)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Address', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('website', models.CharField(default='', max_length=60)),
                ('email', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('key', models.CharField(default=api.models.random_string, max_length=128, unique=True)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Address', unique=True)),
                ('hiring', models.ManyToManyField(related_name='hiring', to='api.College')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Company_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default='False')),
                ('is_HR', models.BooleanField(default='True')),
                ('share', models.CharField(default='1000', max_length=4)),
                ('added_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.Company_User')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
            },
        ),
        migrations.CreateModel(
            name='Custom_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Address', unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=60)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(blank=True, max_length=10)),
                ('performance', models.CharField(max_length=3)),
                ('name', models.CharField(default='None', max_length=20)),
                ('type_of_degree', models.CharField(default='None', max_length=20)),
                ('description', models.TextField()),
                ('specialise', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commits', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('repositories', models.IntegerField()),
                ('following', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('hired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications', models.IntegerField(default=0)),
                ('selected', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default='False')),
                ('denied', models.BooleanField(default='False')),
                ('allowed', models.BooleanField(default='False')),
                ('certificate', models.BooleanField(default='False')),
                ('flexible_work_hours', models.BooleanField(default='False')),
                ('letter_of_recommendation', models.BooleanField(default='False')),
                ('free_snacks', models.BooleanField(default='False')),
                ('informal_dress_code', models.BooleanField(default='False')),
                ('PPO', models.BooleanField(default='False')),
                ('stripend_rate', models.CharField(default='None', max_length=20)),
                ('fixed', models.BooleanField(default='False')),
                ('negotiable', models.BooleanField(default='False')),
                ('performance_based', models.BooleanField(default='False')),
                ('catagory', models.CharField(default='None', max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('responsibilities', models.TextField(default='')),
                ('stripend', models.CharField(default='0', max_length=6)),
                ('location', models.CharField(default='New Delhi', max_length=50)),
                ('code', models.CharField(blank=True, max_length=4)),
                ('available', models.ManyToManyField(related_name='internships', to='api.College')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Company', verbose_name='Company')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Company_User', verbose_name='Company User')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=60)),
                ('organization', models.CharField(max_length=90)),
                ('location', models.CharField(max_length=90)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField()),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Intern')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('start', models.CharField(max_length=10)),
                ('end', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Intern')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=50)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Internship', verbose_name='Internship')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Custom_User', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='1', max_length=20)),
                ('selected', models.BooleanField(default='False')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Intern')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Internship', verbose_name='Internship')),
            ],
        ),
        migrations.AddField(
            model_name='internship',
            name='skills',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='intern',
            name='skills',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AddField(
            model_name='intern',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Custom_User'),
        ),
        migrations.AddField(
            model_name='github',
            name='intern',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Intern'),
        ),
        migrations.AddField(
            model_name='degree',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Intern'),
        ),
        migrations.AddField(
            model_name='company_user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Custom_User', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Submission', verbose_name='Submission'),
        ),
    ]
