# Generated by Django 2.0.6 on 2018-08-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='is_main',
            new_name='in_main',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='applications',
        ),
    ]
