# Generated by Django 2.0.6 on 2018-06-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180625_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_user',
            name='added_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Company_User', verbose_name='User'),
        ),
    ]
