# Generated by Django 2.0.7 on 2018-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180721_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_user',
            name='share',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
