# Generated by Django 2.0.6 on 2018-06-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='internship_id',
            new_name='internship',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='internship_id',
            new_name='internship',
        ),
    ]
