# Generated by Django 2.0.7 on 2018-07-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180721_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='college',
        ),
    ]
