# Generated by Django 2.0.6 on 2018-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180625_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='api.Skill'),
        ),
    ]
