# Generated by Django 2.0.6 on 2018-06-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180620_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameField(
            model_name='hiring',
            old_name='sub',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='intern',
            old_name='sub',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='degrees',
        ),
        migrations.AddField(
            model_name='intern',
            name='skills',
            field=models.ManyToManyField(to='api.Skill'),
        ),
    ]
