# Generated by Django 2.0.7 on 2018-07-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180721_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='college',
            new_name='sub',
        ),
    ]
