# Generated by Django 2.0.6 on 2018-06-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180621_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub', models.CharField(max_length=200)),
                ('location', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
