# Generated by Django 2.0.7 on 2018-07-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180721_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='allowed',
            new_name='in_main',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='denied',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='selected',
        ),
    ]
