# Generated by Django 2.0.6 on 2018-06-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteadmin',
            name='email',
        ),
    ]
