# Generated by Django 2.0.6 on 2018-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180723_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='in_main',
            new_name='is_main',
        ),
        migrations.AddField(
            model_name='internship',
            name='allowed',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='internship',
            name='applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internship',
            name='denied',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='internship',
            name='selected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internship',
            name='available',
            field=models.ManyToManyField(blank=True, null=True, related_name='internships', to='api.Sub'),
        ),
    ]
