# Generated by Django 2.0.6 on 2018-06-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_siteadmin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiring',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='hiring',
            field=models.ManyToManyField(related_name='hiring', to='api.College'),
        ),
        migrations.AddField(
            model_name='internship',
            name='available',
            field=models.ManyToManyField(related_name='internships', to='api.College'),
        ),
        migrations.DeleteModel(
            name='Hiring',
        ),
    ]
