# Generated by Django 2.0.6 on 2018-06-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180624_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='skills',
            field=models.ManyToManyField(to='api.Skill'),
        ),
    ]
