# Generated by Django 2.0.7 on 2018-07-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180724_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='in_main',
            field=models.BooleanField(default='False'),
        ),
    ]
