# Generated by Django 2.0.6 on 2018-06-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180626_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='stripend',
            new_name='stipend',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='stripend_rate',
            new_name='stipend_rate',
        ),
    ]
