# Generated by Django 2.0.7 on 2018-07-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_internship_in_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteadmin',
            name='user',
        ),
        migrations.DeleteModel(
            name='SiteAdmin',
        ),
    ]
