# Generated by Django 2.0.6 on 2018-06-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180626_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='id_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
