# Generated by Django 2.0.6 on 2018-06-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_internship_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='code',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
