# Generated by Django 2.0.7 on 2018-07-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180724_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='api.Sub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Custom_User', verbose_name='User')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
