# Generated by Django 2.0.6 on 2018-06-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180629_0818'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('internship', 'intern')},
        ),
    ]
