# Generated by Django 2.0.6 on 2018-06-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180629_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Submission', verbose_name='Submission'),
        ),
    ]
