# Generated by Django 2.0.6 on 2018-07-05 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180705_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='applications_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internship',
            name='visibility',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
