# Generated by Django 2.0.6 on 2018-07-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180705_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='github',
            name='commits',
        ),
        migrations.AddField(
            model_name='github',
            name='collaborators',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='github',
            name='handle',
            field=models.CharField(default='Gaurav', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='github',
            name='origanization',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='github',
            name='origanization_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='github',
            name='owned_private',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='github',
            name='owned_public_repos',
            field=models.IntegerField(default=0),
        ),
    ]
