# Generated by Django 2.0.6 on 2018-07-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180706_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
