# Generated by Django 2.0.6 on 2018-07-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_github_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='owned_private',
            new_name='owned_private_repo',
        ),
    ]
