# Generated by Django 2.0.6 on 2018-07-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20180706_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company_user',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='degree',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='github',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intern',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internship',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteadmin',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
