# Generated by Django 2.0.6 on 2018-07-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180709_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='stream',
            field=models.CharField(default='Computer Science', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degree',
            name='specialise',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
