# Generated by Django 2.0.6 on 2018-07-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180709_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ManyToManyField(to='api.Address'),
        ),
    ]
