# Generated by Django 2.0.6 on 2018-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180709_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='locations',
            field=models.ManyToManyField(to='api.Address'),
        ),
    ]
