# Generated by Django 2.0.6 on 2018-07-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_internship_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.Address', unique=True),
        ),
    ]
