# Generated by Django 2.0.7 on 2018-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180709_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='placeholder',
            field=models.CharField(default='', max_length=200),
        ),
    ]
