# Generated by Django 2.0.7 on 2018-07-11 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_question_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Address'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='skills',
            field=models.ManyToManyField(to='api.Skill'),
        ),
        migrations.AlterField(
            model_name='question',
            name='placeholder',
            field=models.CharField(default='', max_length=50),
        ),
    ]
