# Generated by Django 2.0.7 on 2018-07-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180711_0534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='start',
            new_name='deadline',
        ),
    ]
