# Generated by Django 2.0.7 on 2018-07-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180712_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='api.Internship', verbose_name='Internship'),
        ),
    ]
