# Generated by Django 2.0.7 on 2018-07-16 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180716_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Custom_User'),
        ),
    ]
