# Generated by Django 2.0.7 on 2018-07-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20180716_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='company_user',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Company User', 'verbose_name_plural': 'Company Users'},
        ),
        migrations.AlterModelOptions(
            name='custom_user',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='forgotpassword',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='github',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='intern',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='siteadmin',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-updated_at']},
        ),
    ]
