# Generated by Django 2.0.6 on 2018-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20180705_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='expires',
            field=models.IntegerField(default=2592000),
        ),
    ]
